-- Baseline: the app's tables as they stood when deploy-time migrations were
-- introduced, generated by `node tools/migrate.js --dump-baseline` from
-- explorer.cruc4oigszuh.eu-north-1.rds.amazonaws.com/jfa on 2026-09-21. Tables: src/db/migrate/baseline-tables.json.
--
-- Executed only on an empty database. An existing database records it
-- without running it (`--adopt`, after `--verify-baseline` is clean). Do not
-- edit it: schema changes are new files after it.

CREATE TABLE IF NOT EXISTS `adjusted_sales` (
  `id` int NOT NULL AUTO_INCREMENT,
  `asin` varchar(20) NOT NULL,
  `country` varchar(8) NOT NULL,
  `adjusted_sales` decimal(12,2) NOT NULL,
  `note` varchar(500) DEFAULT NULL,
  `created_by_email` varchar(255) DEFAULT NULL,
  `updated_by_email` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_asin_country` (`asin`,`country`),
  KEY `idx_asin` (`asin`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `air_shipments` (
  `awb_number` varchar(20) NOT NULL,
  `reference` varchar(128) DEFAULT NULL,
  `airline_name` varchar(255) DEFAULT NULL,
  `airline_iata` varchar(4) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `origin_name` varchar(255) DEFAULT NULL,
  `origin_iata` varchar(4) DEFAULT NULL,
  `origin_country` varchar(2) DEFAULT NULL,
  `destination_name` varchar(255) DEFAULT NULL,
  `destination_iata` varchar(4) DEFAULT NULL,
  `destination_country` varchar(2) DEFAULT NULL,
  `transshipments` json DEFAULT NULL,
  `current_lat` decimal(10,6) DEFAULT NULL,
  `current_lng` decimal(10,6) DEFAULT NULL,
  `departure_date` datetime DEFAULT NULL,
  `departure_is_actual` tinyint(1) DEFAULT NULL,
  `departure_initial` datetime DEFAULT NULL,
  `arrival_date` datetime DEFAULT NULL,
  `arrival_is_actual` tinyint(1) DEFAULT NULL,
  `eta` datetime DEFAULT NULL,
  `ata` datetime DEFAULT NULL,
  `eta_initial` datetime DEFAULT NULL,
  `total_transit_time` int DEFAULT NULL,
  `transit_percentage` int DEFAULT NULL,
  `ts_count` int DEFAULT NULL,
  `milestones` json DEFAULT NULL,
  `tags` json DEFAULT NULL,
  `checked_at` datetime DEFAULT NULL,
  `shipsgo_id` varchar(100) DEFAULT NULL,
  `route_geojson` json DEFAULT NULL,
  `raw` json DEFAULT NULL,
  `fetched_at` datetime DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`awb_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `amazon_active_listings` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `date_ran` date NOT NULL,
  `country` varchar(5) NOT NULL,
  `company` varchar(50) NOT NULL,
  `asin` varchar(20) NOT NULL,
  `sku` varchar(50) NOT NULL DEFAULT '',
  `fnsku` varchar(20) NOT NULL DEFAULT '',
  `product_name` varchar(500) NOT NULL DEFAULT '',
  `status` varchar(20) NOT NULL DEFAULT '',
  `price` decimal(10,2) NOT NULL DEFAULT '0.00',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_unique` (`date_ran`,`country`,`company`,`asin`,`sku`),
  KEY `idx_asin` (`asin`),
  KEY `idx_company_country` (`company`,`country`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `amazon_report_jobs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `batch_date` date NOT NULL,
  `account` varchar(64) NOT NULL,
  `country` varchar(8) NOT NULL,
  `report_type` varchar(32) NOT NULL,
  `marketplace_id` varchar(32) DEFAULT NULL,
  `report_id` varchar(64) DEFAULT NULL,
  `document_id` varchar(128) DEFAULT NULL,
  `status` enum('REQUESTED','DONE','PROCESSED','FAILED') NOT NULL DEFAULT 'REQUESTED',
  `result_cache` longtext,
  `claim_token` varchar(64) DEFAULT NULL,
  `claimed_at` datetime DEFAULT NULL,
  `requested_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `polled_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `processed_at` datetime DEFAULT NULL,
  `error` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_batch_job` (`batch_date`,`account`,`country`,`report_type`),
  KEY `idx_status_batch` (`status`,`batch_date`),
  KEY `idx_claim` (`claim_token`,`claimed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `amazon_stock_country_snapshots` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `date_ran` date NOT NULL,
  `country` varchar(5) NOT NULL,
  `asin` varchar(20) NOT NULL DEFAULT '',
  `company` varchar(50) NOT NULL DEFAULT 'JFA',
  `fnsku` varchar(1000) NOT NULL DEFAULT '',
  `sku` varchar(1000) NOT NULL DEFAULT '',
  `condition_type` varchar(20) NOT NULL DEFAULT '',
  `fulfillable` int NOT NULL DEFAULT '0',
  `inbound_working` int NOT NULL DEFAULT '0',
  `inbound_shipped` int NOT NULL DEFAULT '0',
  `inbound_receiving` int NOT NULL DEFAULT '0',
  `reserved` int NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_unique` (`date_ran`,`country`,`asin`,`company`),
  KEY `idx_asin_date` (`asin`,`date_ran`),
  KEY `idx_country_date` (`country`,`date_ran`),
  KEY `idx_asin` (`asin`),
  KEY `idx_date_ran` (`date_ran`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `amazon_stock_raw_snapshots` (
  `date_ran` date NOT NULL,
  `country` varchar(5) NOT NULL,
  `asin` varchar(20) NOT NULL,
  `company` varchar(50) NOT NULL DEFAULT 'JFA',
  `fulfillable` int DEFAULT '0',
  PRIMARY KEY (`date_ran`,`country`,`asin`,`company`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `app_migrations` (
  `name` varchar(64) NOT NULL,
  `applied_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `audit_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `entity_type` varchar(32) NOT NULL,
  `entity_id` int NOT NULL,
  `action` varchar(64) NOT NULL,
  `before_json` json DEFAULT NULL,
  `after_json` json DEFAULT NULL,
  `user_email` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_entity` (`entity_type`,`entity_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `companies` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `address_lines` json DEFAULT NULL,
  `country` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `containers` (
  `container_number` varchar(50) NOT NULL,
  `bl_number` varchar(100) DEFAULT NULL,
  `booking_ref` varchar(100) DEFAULT NULL,
  `vessel_imo` varchar(20) DEFAULT NULL,
  `vessel_name` varchar(255) DEFAULT NULL,
  `voyage` varchar(50) DEFAULT NULL,
  `shipping_line` varchar(255) DEFAULT NULL,
  `pol_name` varchar(255) DEFAULT NULL,
  `pol_locode` varchar(10) DEFAULT NULL,
  `pod_name` varchar(255) DEFAULT NULL,
  `pod_locode` varchar(10) DEFAULT NULL,
  `transshipments` json DEFAULT NULL,
  `current_lat` decimal(10,6) DEFAULT NULL,
  `current_lng` decimal(10,6) DEFAULT NULL,
  `departure_date` datetime DEFAULT NULL,
  `departure_is_actual` tinyint(1) DEFAULT NULL,
  `arrival_date` datetime DEFAULT NULL,
  `arrival_is_actual` tinyint(1) DEFAULT NULL,
  `eta` datetime DEFAULT NULL,
  `ata` datetime DEFAULT NULL,
  `milestones` json DEFAULT NULL,
  `co2_emissions` decimal(12,2) DEFAULT NULL,
  `delay_status` varchar(50) DEFAULT NULL,
  `container_size_type` varchar(50) DEFAULT NULL,
  `demurrage_info` json DEFAULT NULL,
  `shipsgo_id` varchar(100) DEFAULT NULL,
  `raw` json DEFAULT NULL,
  `fetched_at` datetime DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `carrier_scac` varchar(10) DEFAULT NULL,
  `carrier_ref_number` varchar(100) DEFAULT NULL,
  `bl_type` varchar(50) DEFAULT NULL,
  `service_name` varchar(100) DEFAULT NULL,
  `pol_country` varchar(2) DEFAULT NULL,
  `pod_country` varchar(2) DEFAULT NULL,
  `por_name` varchar(255) DEFAULT NULL,
  `por_locode` varchar(10) DEFAULT NULL,
  `final_delivery_name` varchar(255) DEFAULT NULL,
  `final_delivery_locode` varchar(10) DEFAULT NULL,
  `discharge_terminal` varchar(255) DEFAULT NULL,
  `carrier_last_updated` datetime DEFAULT NULL,
  `seal_number` varchar(100) DEFAULT NULL,
  `holds` json DEFAULT NULL,
  `free_time_info` json DEFAULT NULL,
  `tags` json DEFAULT NULL,
  `total_transit_days` int DEFAULT NULL,
  `eta_initial` datetime DEFAULT NULL,
  `route_geojson` json DEFAULT NULL,
  PRIMARY KEY (`container_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `daily_alerts` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `dedup_key` varchar(255) NOT NULL,
  `type` varchar(32) NOT NULL,
  `severity` varchar(16) NOT NULL DEFAULT 'today',
  `event_date` date NOT NULL,
  `title` varchar(255) NOT NULL,
  `body` varchar(1000) DEFAULT NULL,
  `entity_type` varchar(32) DEFAULT NULL,
  `entity_id` varchar(100) DEFAULT NULL,
  `meta` json DEFAULT NULL,
  `acknowledged_at` datetime DEFAULT NULL,
  `acknowledged_by` varchar(255) DEFAULT NULL,
  `snoozed_until` datetime DEFAULT NULL,
  `dismissed_at` datetime DEFAULT NULL,
  `resolved_at` datetime DEFAULT NULL,
  `last_seen_at` datetime DEFAULT NULL,
  `last_action` varchar(16) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `action_note` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dedup` (`dedup_key`),
  KEY `idx_event_date` (`event_date`),
  KEY `idx_type` (`type`),
  KEY `idx_last_seen` (`last_seen_at`),
  KEY `idx_lifecycle` (`dismissed_at`,`resolved_at`,`snoozed_until`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `draft_container_allocations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `draft_container_name` varchar(100) NOT NULL,
  `allocated` int NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_draft` (`order_id`,`draft_container_name`),
  KEY `idx_draft_name` (`draft_container_name`),
  KEY `idx_order_id` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `draft_container_document_sends` (
  `id` int NOT NULL AUTO_INCREMENT,
  `draft_container_document_id` int NOT NULL,
  `sent_to` json NOT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `front_message_uid` varchar(128) DEFAULT NULL,
  `front_conversation_id` varchar(64) DEFAULT NULL,
  `sent_by_email` varchar(255) DEFAULT NULL,
  `sent_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_document_id` (`draft_container_document_id`),
  KEY `idx_sent_at` (`sent_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `draft_container_documents` (
  `id` int NOT NULL AUTO_INCREMENT,
  `draft_container_name` varchar(100) NOT NULL,
  `version` int NOT NULL,
  `s3_key` varchar(500) NOT NULL,
  `public_url` varchar(1000) DEFAULT NULL,
  `file_size` int DEFAULT NULL,
  `generated_by_email` varchar(255) DEFAULT NULL,
  `generated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  `type` varchar(32) NOT NULL DEFAULT 'quote',
  `supplier` varchar(255) DEFAULT NULL,
  `batch_id` varchar(64) DEFAULT NULL,
  `csv_s3_key` varchar(500) DEFAULT NULL,
  `csv_public_url` varchar(1000) DEFAULT NULL,
  `csv_file_size` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_draft_version` (`draft_container_name`,`version`),
  KEY `idx_batch_id` (`batch_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `draft_containers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `created_by_email` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `last_activity_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `closed_reason` varchar(16) DEFAULT NULL,
  `closed_at` datetime DEFAULT NULL,
  `closed_by_email` varchar(255) DEFAULT NULL,
  `container_number` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_name` (`name`),
  KEY `idx_last_activity` (`last_activity_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `email_receipt_reminders` (
  `id` int NOT NULL AUTO_INCREMENT,
  `email_receipt_id` int NOT NULL,
  `reminder_number` int NOT NULL,
  `sent_to` text,
  `subject` varchar(500) DEFAULT NULL,
  `front_message_uid` varchar(255) DEFAULT NULL,
  `front_conversation_id` varchar(255) DEFAULT NULL,
  `sent_by_email` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_receipt` (`email_receipt_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `email_receipts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `token` varchar(64) NOT NULL,
  `email_type` varchar(48) NOT NULL,
  `send_table` varchar(64) DEFAULT NULL,
  `send_id` int DEFAULT NULL,
  `sent_to` text,
  `subject` varchar(500) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `clicked_at` datetime DEFAULT NULL,
  `click_count` int NOT NULL DEFAULT '0',
  `clicked_user_agent` varchar(500) DEFAULT NULL,
  `clicked_ip` varchar(64) DEFAULT NULL,
  `opened_at` datetime DEFAULT NULL,
  `open_count` int NOT NULL DEFAULT '0',
  `confirmed_at` datetime DEFAULT NULL,
  `confirmed_ip` varchar(64) DEFAULT NULL,
  `confirmed_user_agent` varchar(500) DEFAULT NULL,
  `reminder_count` int NOT NULL DEFAULT '0',
  `last_reminder_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_token` (`token`),
  KEY `idx_send` (`send_table`,`send_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `email_templates` (
  `id` int NOT NULL AUTO_INCREMENT,
  `template_key` varchar(64) NOT NULL,
  `name` varchar(255) NOT NULL,
  `category` varchar(64) DEFAULT NULL,
  `description` text,
  `subject` varchar(500) DEFAULT NULL,
  `body_html` mediumtext NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_template_key` (`template_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `front_email_index` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `conversation_id` varchar(100) NOT NULL,
  `subject` varchar(512) DEFAULT NULL,
  `from_email` varchar(255) DEFAULT NULL,
  `front_url` varchar(255) DEFAULT NULL,
  `message_count` int NOT NULL DEFAULT '0',
  `last_message_at` datetime DEFAULT NULL,
  `matched_order_count` int NOT NULL DEFAULT '0',
  `order_ids` json DEFAULT NULL,
  `ambiguous` tinyint(1) NOT NULL DEFAULT '0',
  `gemini_used` tinyint(1) NOT NULL DEFAULT '0',
  `gemini_confidence` decimal(4,3) DEFAULT NULL,
  `signals` json DEFAULT NULL,
  `scanned_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_message_ms` bigint DEFAULT NULL,
  `body_full` mediumtext,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_convo` (`conversation_id`),
  KEY `idx_last_msg` (`last_message_at`),
  FULLTEXT KEY `ftx_body` (`subject`,`body_full`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `front_email_scan_state` (
  `id` tinyint NOT NULL,
  `last_run_ts` bigint DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `front_status_import_state` (
  `id` tinyint NOT NULL,
  `last_run_ts` bigint DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `front_status_imports` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `source_ref` varchar(255) NOT NULL,
  `conversation_id` varchar(100) DEFAULT NULL,
  `message_id` varchar(100) DEFAULT NULL,
  `from_email` varchar(255) DEFAULT NULL,
  `subject` varchar(512) DEFAULT NULL,
  `received_at` datetime DEFAULT NULL,
  `extracted_po` varchar(100) DEFAULT NULL,
  `po_found` tinyint(1) DEFAULT NULL,
  `inferred_status` varchar(32) DEFAULT NULL,
  `status_stated` tinyint(1) DEFAULT NULL,
  `confidence` decimal(4,3) DEFAULT NULL,
  `rationale` varchar(1000) DEFAULT NULL,
  `matched_order_count` int NOT NULL DEFAULT '0',
  `order_ids` json DEFAULT NULL,
  `alert_ids` json DEFAULT NULL,
  `model_used` varchar(64) DEFAULT NULL,
  `usage_json` json DEFAULT NULL,
  `outcome` varchar(24) NOT NULL DEFAULT 'pending',
  `error_message` varchar(1000) DEFAULT NULL,
  `source_meta` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_source_ref` (`source_ref`),
  KEY `idx_outcome` (`outcome`),
  KEY `idx_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `mintsoft_locations` (
  `location_id` int NOT NULL,
  `warehouse_id` int NOT NULL,
  `warehouse_name` varchar(100) DEFAULT NULL,
  `warehouse_code` varchar(50) DEFAULT NULL,
  `warehouse_active` tinyint(1) DEFAULT '1',
  `name` varchar(200) DEFAULT NULL,
  `location_name` varchar(200) DEFAULT NULL,
  `pick_sequence` int DEFAULT NULL,
  `location_type_id` int DEFAULT NULL,
  `last_synced` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_warehouse` (`warehouse_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `order_emails` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` bigint NOT NULL,
  `conversation_id` varchar(100) NOT NULL,
  `subject` varchar(512) DEFAULT NULL,
  `preview` varchar(1000) DEFAULT NULL,
  `from_email` varchar(255) DEFAULT NULL,
  `participants` json DEFAULT NULL,
  `direction` varchar(16) DEFAULT NULL,
  `front_url` varchar(255) DEFAULT NULL,
  `match_tier` varchar(16) NOT NULL DEFAULT 'product',
  `match_basis` json DEFAULT NULL,
  `source` varchar(16) NOT NULL DEFAULT 'rule',
  `confidence` decimal(4,3) DEFAULT NULL,
  `message_count` int NOT NULL DEFAULT '0',
  `first_message_at` datetime DEFAULT NULL,
  `last_message_at` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_convo_order` (`conversation_id`,`order_id`),
  KEY `idx_order_recent` (`order_id`,`last_message_at`),
  KEY `idx_convo` (`conversation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `order_qc_reports` (
  `id` int NOT NULL AUTO_INCREMENT,
  `qc_report_id` int NOT NULL,
  `order_id` int NOT NULL,
  `jf_code` varchar(50) DEFAULT NULL,
  `lot_number` varchar(255) DEFAULT NULL,
  `qc_result` varchar(16) NOT NULL,
  `result_detail` varchar(1000) DEFAULT NULL,
  `match_method` varchar(16) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_report_order` (`qc_report_id`,`order_id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_qc_report_id` (`qc_report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `order_receipts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `jf_code` varchar(50) DEFAULT NULL,
  `quantity` int NOT NULL,
  `location_id` int NOT NULL,
  `warehouse_id` int NOT NULL,
  `asn_id` int DEFAULT NULL,
  `asn_item_id` int DEFAULT NULL,
  `idempotency_key` varchar(64) DEFAULT NULL,
  `batch_no` varchar(255) DEFAULT NULL,
  `expiry_date` date DEFAULT NULL,
  `received_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `type` varchar(16) NOT NULL DEFAULT 'received',
  `quarantined` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_idempotency` (`order_id`,`idempotency_key`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_jf_code` (`jf_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `orders` (
  `id` int NOT NULL AUTO_INCREMENT,
  `jf_code` varchar(50) DEFAULT NULL,
  `asin` varchar(20) DEFAULT NULL,
  `product_name` varchar(255) DEFAULT NULL,
  `quantity` int NOT NULL DEFAULT '0',
  `status` varchar(50) NOT NULL DEFAULT 'SCHEDULED',
  `po_number` varchar(100) DEFAULT NULL,
  `supplier` varchar(255) DEFAULT NULL,
  `container_number` varchar(100) DEFAULT NULL,
  `vessel_name` varchar(255) DEFAULT NULL,
  `eta` date DEFAULT NULL,
  `cbm_per_unit` decimal(10,6) DEFAULT NULL,
  `notes` text,
  `dates` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `delivery_date` datetime DEFAULT NULL,
  `lot_number` varchar(255) DEFAULT NULL,
  `mfg_date` date DEFAULT NULL,
  `exp_date` date DEFAULT NULL,
  `delivery_time` varchar(100) DEFAULT NULL,
  `container_status` varchar(100) DEFAULT NULL,
  `booking_status` varchar(100) DEFAULT NULL,
  `arrived_date` date DEFAULT NULL,
  `external_container_number` varchar(255) DEFAULT NULL,
  `order_cbm` decimal(10,3) DEFAULT NULL,
  `port` varchar(255) DEFAULT NULL,
  `carton_cbm` decimal(10,6) DEFAULT NULL,
  `units_per_carton` int DEFAULT NULL,
  `pack_size` varchar(100) DEFAULT NULL,
  `scheduled_date` date DEFAULT NULL,
  `po_date` date DEFAULT NULL,
  `qc_status` varchar(100) DEFAULT NULL,
  `qc_date` date DEFAULT NULL,
  `qc_invoice_number` varchar(100) DEFAULT NULL,
  `purchase_order_id` int DEFAULT NULL,
  `unit_price` decimal(10,4) DEFAULT NULL,
  `actual_ready_date` date DEFAULT NULL,
  `estimated_departure_date` date DEFAULT NULL,
  `shipped_date` date DEFAULT NULL,
  `ordered_date` date DEFAULT NULL,
  `estimated_ready_date` date DEFAULT NULL,
  `artwork_confirmed_date` date DEFAULT NULL,
  `awb_number` varchar(50) DEFAULT NULL,
  `carton_weight` decimal(10,3) DEFAULT NULL,
  `carton_height` decimal(10,3) DEFAULT NULL,
  `carton_width` decimal(10,3) DEFAULT NULL,
  `carton_depth` decimal(10,3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_container` (`container_number`),
  KEY `idx_id` (`jf_code`),
  KEY `idx_purchase_order_id` (`purchase_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `planned_container_allocations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `planned_container_name` varchar(100) NOT NULL,
  `allocated` int NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_planned` (`order_id`,`planned_container_name`),
  KEY `idx_planned_name` (`planned_container_name`),
  KEY `idx_order_id` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `po_sent_webhooks` (
  `po_number` varchar(100) NOT NULL,
  `jf_code` varchar(50) NOT NULL,
  `fired_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`po_number`,`jf_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `purchase_order_document_sends` (
  `id` int NOT NULL AUTO_INCREMENT,
  `purchase_order_document_id` int NOT NULL,
  `sent_to` json NOT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `front_message_uid` varchar(128) DEFAULT NULL,
  `front_conversation_id` varchar(64) DEFAULT NULL,
  `sent_by_email` varchar(255) DEFAULT NULL,
  `sent_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_document_id` (`purchase_order_document_id`),
  KEY `idx_sent_at` (`sent_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `purchase_order_documents` (
  `id` int NOT NULL AUTO_INCREMENT,
  `purchase_order_id` int NOT NULL,
  `version` int NOT NULL,
  `s3_key` varchar(500) NOT NULL,
  `public_url` varchar(1000) DEFAULT NULL,
  `file_size` int DEFAULT NULL,
  `generated_by_email` varchar(255) DEFAULT NULL,
  `generated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_po_version` (`purchase_order_id`,`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `purchase_order_invoice_checks` (
  `id` int NOT NULL AUTO_INCREMENT,
  `purchase_order_invoice_id` int NOT NULL,
  `status` enum('pending','succeeded','failed') NOT NULL,
  `verdict` varchar(32) DEFAULT NULL,
  `discrepancy_count` int DEFAULT NULL,
  `result_json` json DEFAULT NULL,
  `model_used` varchar(64) DEFAULT NULL,
  `input_tokens` int DEFAULT NULL,
  `output_tokens` int DEFAULT NULL,
  `total_tokens` int DEFAULT NULL,
  `error_code` varchar(64) DEFAULT NULL,
  `error_message` text,
  `triggered_by` varchar(32) DEFAULT NULL,
  `triggered_by_email` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_invoice_id` (`purchase_order_invoice_id`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `purchase_order_invoice_payments` (
  `id` int NOT NULL AUTO_INCREMENT,
  `purchase_order_invoice_id` int NOT NULL,
  `purchase_order_id` int NOT NULL,
  `payment_type` varchar(32) DEFAULT NULL,
  `amount_due` decimal(14,2) DEFAULT NULL,
  `currency` char(3) DEFAULT NULL,
  `deposit_percentage` decimal(6,3) DEFAULT NULL,
  `invoice_total` decimal(14,2) DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `due_terms` varchar(500) DEFAULT NULL,
  `beneficiary_name` varchar(255) DEFAULT NULL,
  `bank_name` varchar(255) DEFAULT NULL,
  `bank_address` varchar(500) DEFAULT NULL,
  `account_number` varchar(100) DEFAULT NULL,
  `iban` varchar(64) DEFAULT NULL,
  `swift_bic` varchar(32) DEFAULT NULL,
  `intermediary_bank` varchar(255) DEFAULT NULL,
  `payment_reference` varchar(255) DEFAULT NULL,
  `raw_terms_text` text,
  `payment_status` enum('pending','arranged','paid','skipped') NOT NULL DEFAULT 'pending',
  `extracted_from_check_id` int DEFAULT NULL,
  `model_used` varchar(64) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_invoice` (`purchase_order_invoice_id`),
  KEY `idx_purchase_order_id` (`purchase_order_id`),
  KEY `idx_payment_status` (`payment_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `purchase_order_invoices` (
  `id` int NOT NULL AUTO_INCREMENT,
  `purchase_order_id` int NOT NULL,
  `filename` varchar(255) NOT NULL,
  `s3_key` varchar(500) NOT NULL,
  `public_url` varchar(1000) DEFAULT NULL,
  `content_type` varchar(128) DEFAULT NULL,
  `file_size` int DEFAULT NULL,
  `notes` text,
  `uploaded_by_email` varchar(255) DEFAULT NULL,
  `uploaded_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_purchase_order_id` (`purchase_order_id`),
  KEY `idx_uploaded_at` (`uploaded_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `purchase_order_payments` (
  `id` int NOT NULL AUTO_INCREMENT,
  `purchase_order_id` int NOT NULL,
  `filename` varchar(255) NOT NULL,
  `s3_key` varchar(500) NOT NULL,
  `public_url` varchar(1000) DEFAULT NULL,
  `content_type` varchar(128) DEFAULT NULL,
  `file_size` int DEFAULT NULL,
  `notes` text,
  `uploaded_by_email` varchar(255) DEFAULT NULL,
  `uploaded_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_purchase_order_id` (`purchase_order_id`),
  KEY `idx_uploaded_at` (`uploaded_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `purchase_order_signed_pi_sends` (
  `id` int NOT NULL AUTO_INCREMENT,
  `purchase_order_signed_pi_id` int NOT NULL,
  `sent_to` json NOT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `front_message_uid` varchar(128) DEFAULT NULL,
  `front_conversation_id` varchar(64) DEFAULT NULL,
  `sent_by_email` varchar(255) DEFAULT NULL,
  `sent_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_signed_pi_id` (`purchase_order_signed_pi_id`),
  KEY `idx_sent_at` (`sent_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `purchase_order_signed_pis` (
  `id` int NOT NULL AUTO_INCREMENT,
  `purchase_order_id` int NOT NULL,
  `filename` varchar(255) NOT NULL,
  `s3_key` varchar(500) NOT NULL,
  `public_url` varchar(1000) DEFAULT NULL,
  `content_type` varchar(128) DEFAULT NULL,
  `file_size` int DEFAULT NULL,
  `notes` text,
  `uploaded_by_email` varchar(255) DEFAULT NULL,
  `uploaded_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_purchase_order_id` (`purchase_order_id`),
  KEY `idx_uploaded_at` (`uploaded_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `purchase_orders` (
  `id` int NOT NULL AUTO_INCREMENT,
  `po_number` varchar(100) NOT NULL,
  `supplier` varchar(255) DEFAULT NULL,
  `notes` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `currency` char(3) DEFAULT 'USD',
  `shipping_total` decimal(10,2) DEFAULT '0.00',
  `company_id` int DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_po_number` (`po_number`),
  KEY `idx_company_id` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `qc_reports` (
  `id` int NOT NULL AUTO_INCREMENT,
  `filename` varchar(200) NOT NULL,
  `s3_key` varchar(500) NOT NULL,
  `public_url` varchar(1000) DEFAULT NULL,
  `content_type` varchar(100) DEFAULT NULL,
  `file_size` int DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'awaiting_upload',
  `supplier` varchar(255) DEFAULT NULL,
  `report_title` varchar(255) DEFAULT NULL,
  `inspection_date` varchar(100) DEFAULT NULL,
  `model_used` varchar(64) DEFAULT NULL,
  `item_count` int DEFAULT NULL,
  `matched_count` int DEFAULT NULL,
  `result_json` json DEFAULT NULL,
  `error_message` text,
  `uploaded_by_email` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `analyzed_at` timestamp NULL DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `source` varchar(32) DEFAULT NULL,
  `source_ref` varchar(255) DEFAULT NULL,
  `source_meta` json DEFAULT NULL,
  `source_received_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_source_ref` (`source_ref`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `quality_assurance_document_sends` (
  `id` int NOT NULL AUTO_INCREMENT,
  `quality_assurance_document_id` int NOT NULL,
  `sent_to` json NOT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `front_message_uid` varchar(128) DEFAULT NULL,
  `front_conversation_id` varchar(64) DEFAULT NULL,
  `sent_by_email` varchar(255) DEFAULT NULL,
  `sent_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_qa_document_id` (`quality_assurance_document_id`),
  KEY `idx_sent_at` (`sent_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `quality_assurance_documents` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ref` varchar(100) DEFAULT NULL,
  `version` int NOT NULL,
  `order_ids` json NOT NULL,
  `order_ids_key` varchar(255) NOT NULL,
  `qc_units` json DEFAULT NULL,
  `s3_key` varchar(500) NOT NULL,
  `public_url` varchar(1000) DEFAULT NULL,
  `file_size` int DEFAULT NULL,
  `comments` text,
  `generated_by_email` varchar(255) DEFAULT NULL,
  `generated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  `draft_container_name` varchar(100) DEFAULT NULL,
  `csv_s3_key` varchar(500) DEFAULT NULL,
  `csv_public_url` varchar(1000) DEFAULT NULL,
  `csv_file_size` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_order_ids_key` (`order_ids_key`,`version`),
  KEY `idx_draft_container_name` (`draft_container_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `shipping_allowed_emails` (
  `id` int NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `display_name` varchar(255) DEFAULT NULL,
  `type` varchar(32) NOT NULL DEFAULT 'standard',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `stock_snapshots` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `date_ran` date NOT NULL,
  `jf_code` varchar(255) NOT NULL,
  `asin` varchar(50) NOT NULL DEFAULT '',
  `sku` varchar(255) NOT NULL DEFAULT '',
  `product_id` int NOT NULL,
  `warehouse_id` int NOT NULL DEFAULT '0',
  `stock_level` int NOT NULL DEFAULT '0',
  `available` int NOT NULL DEFAULT '0',
  `allocated` int NOT NULL DEFAULT '0',
  `quarantine` int NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_jf_date` (`jf_code`,`date_ran`),
  KEY `idx_asin` (`asin`),
  KEY `idx_asin_date` (`asin`,`date_ran`),
  KEY `idx_date_ran` (`date_ran`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
